name: 'build and test'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and run dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: colcon build
