name: 'build and test'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Test in Devcontainer
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/lgulich/launch_simple
          cacheFrom: ghcr.io/lgulich/launch_simple
          push: never
          runCmd: |
            colcon build
            colcon test
