name: 'CI'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/lgulich/launch_simple
          cacheFrom: ghcr.io/lgulich/launch_simple
          push: never
          runCmd: |
            colcon build
            make -C src/launch_simple/doc html
      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/lgulich/launch_simple
          cacheFrom: ghcr.io/lgulich/launch_simple
          push: never
          runCmd: |
            colcon test
            ros2 launch launch_simple example_default.launch.py
            ros2 launch launch_simple example_simple.launch.py
            ros2 launch launch_simple test_arguments.launch.py
            ros2 launch launch_simple test_composable_node.launch.py
            ros2 launch launch_simple test_includes.launch.py
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'launch_simple/doc/build/html'
  deploy:
    needs: build_and_test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v4
      - uses: actions/deploy-pages@v4
        id: deployment
