name: pre-commit
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python3 -m pip install setuptools
      - uses: pre-commit/action@v3.0.0
